Attempt minimal MIRA unit test (broken)
This doesn't work yet - I need to work out how to specify the conditional parameters.

======================================================================
ERROR: Assemble with MIRA v3.4 ( mira_assembler ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File /mnt/galaxy/galaxy-central/test/functional/test_toolbox.py, line 171, in test_tool
    self.do_it( td, shed_tool_id=shed_tool_id )
  File /mnt/galaxy/galaxy-central/test/functional/test_toolbox.py, line 76, in do_it
    page_inputs =  self.__expand_grouping(testdef.tool.inputs_by_page[0], all_inputs)
  File /mnt/galaxy/galaxy-central/test/functional/test_toolbox.py, line 118, in __expand_grouping
    if declared_inputs[ value.test_param.name ] == case.value:
KeyError: 'use'